version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hogwarts
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: